execute pathogen#infect()

filetype on
syntax on
colorscheme Tomorrow-Night

set tabstop=2
set shiftwidth=2 
set expandtab
set autoindent
set guifont=Menlo:h18
set colorcolumn=90
set showcmd
set cursorline
set laststatus=2
set number
set relativenumber
set showmatch
set autoread

map <C-n> :NERDTreeToggle<CR>

" powerline
" set rtp+=/usr/local/lib/python3.7/site-packages/powerline/bindings/vim
" set laststatus=2
" set t_Co=256
" set guifont=Inconsolata\ for\ Powerline:h15
" let g:Powerline_symbols = 'fancy'
" set encoding=utf-8
" set t_Co=256
" set fillchars+=stl:\ ,stlnc:\
" set term=xterm-256color
" set termencoding=utf-8s

set rtp+=/usr/local/lib/python2.7/site-packages/powerline/bindings/vim

if has("gui_running")
   let s:uname = system("uname")
   if s:uname == "Darwin\n"
      set guifont=Meslo\ LG\ S\ for\ Powerline
   endif
endif