" load vim-plug
source ~/.vim/.plug.vim

filetype on
syntax on
set term=xterm-256color
set termencoding=utf-8
colorscheme Tomorrow-Night

set tabstop=2
set shiftwidth=2 
set expandtab
set autoindent
set guifont=Menlo:h18
set colorcolumn=90
set showcmd
set cursorline
set number
set relativenumber
set showmatch
set autoread

map <C-n> :NERDTreeToggle<CR>

set laststatus=2  "Always display status line
set t_Co=256
" Powerline
source ~/.local/lib/python3.7/site-packages/powerline/bindings/vim/plugin/powerline.vim
if has("gui_running")
   let s:uname = system("uname")
   if s:uname == "Darwin\n"
      set guifont=Meslo\ LG\ S\ for\ Powerline
   endif
endif
